### ISSUE TITLE
Roadmap to Specification

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationRepositoryTemplate#1]
### Introduction

- [x] Read [Introduction](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/Introduction/Introduction.md)

### Preparation

- [x] Read [Introduction to Git and GitHub](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/Introduction2Git/Introduction2Git.md)
- [x] Read [Workflow for Contributing](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/WorkflowForContributing/WorkflowForContributing.md)
- [x] Read [GitFlow Workflow](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/GitFlowWorkflow/GitFlowWorkflow.md)
- [x] Read Issue #8 , create own GitHub account and close the issue
- [x] Read Issue #9 , install Git and close the issue
- [x] Read Issue #10 , install Visual Studio Code and close the issue
- [x] Read Issue #11 , connect Visual Studio Code with GitHub and close the issue
- [x] Make yourself familiar with the [Basic Syntax of Markdown](https://www.markdownguide.org/basic-syntax/)
- [x] Read [Formulating Issues](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingIssues/FormulatingIssues.md)
- [x] Read [Formulating Commit and Merge Request Messages](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingCommitMessages/FormulatingCommitMessages.md)
- [ ] Read Issue #12 , contribute to Content of Introduction

**Comment by kmohr-soprasteria** [comment]
After closing issue #8 the checkbox after "Read Issue" automatically (after a page refresh) changed the icon, but the checkbox was not automatically set.
